:concurrency: 1
:queues:
  - default
  - mailers
:redis:
  url: <%= ENV.fetch("UPSTASH_REDIS_REST_URL").strip %>
  password: <%= ENV.fetch("UPSTASH_REDIS_REST_TOKEN").strip %>
  size: 10  # Increase the pool size
  network_timeout: 5
