require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.6 # Update to your Ruby version
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'config/**/*'
    - 'spec/**/*' # Exclude specs if not using RSpec

Rails:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'spec/**/*' # Exclude specs if not using RSpec

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120