web: bundle exec rails server -p $PORT -e ${RAILS_ENV:-production}
clock: bundle exec clockwork config/clock.rb
# worker: bundle exec sidekiq -C config/sidekiq.yml
# release: bin/rails db:prepare && bundle exec rails db:migrate || echo "Migrations failed - proceeding anyway"