import React from 'react';
import {
  FaBook,
  FaSeedling,
  FaPaw,
  FaPalette,
  FaMusic,
  FaBirthdayCake,
  FaHandHoldingHeart,
  FaTree,
  FaChild,
  FaHandsHelping,
  FaLightbulb,
  FaTint,
  FaCloudSunRain,
  FaUsers,
  FaHeartbeat,
  FaHandHoldingUsd,
  FaMonument,
  FaHome,
  FaBalanceScale,
  FaFirstAid,
  FaMicroscope,
  FaBriefcase,
  FaTractor,
  FaFish,
  FaRing,
  FaBrain,
  FaRecycle,
  FaBus,
  FaSolarPanel,
  FaCity,
  FaFootballBall,
  FaTruck,
  FaLaptop,
  FaBuilding,
  FaUserShield,
  FaWater,
  FaFemale,
  FaMoneyBillWave,
  FaWheelchair,
  FaHandshake,
  FaLeaf,
  FaShieldAlt,
  FaMicrophone,
  FaShoppingCart,
  FaRegMoneyBillAlt,
  FaExchangeAlt,
  FaPiggyBank,
  FaCode,
  FaChartLine,
  FaWallet,
  FaCloud,
  FaUserTie,
  FaTshirt,
  FaHeadset,
  FaPlane,
  FaSatelliteDish,
  FaDumbbell,
  FaRobot,
  FaMicrochip,
  FaQrcode,
  FaCar,
  FaIndustry,
  FaSearchDollar,
  FaMedkit,
  FaGamepad,
  FaUtensils,
  FaGraduationCap,
  FaLock,
  FaMobile,
  FaBitcoin,
} from 'react-icons/fa';

export type Category = {
  value: string;
  label: string;
  icon?: React.ReactNode; // Icon is optional
};

// Helper function to slugify a label into a value
const slugify = (label: string): string => {
  return label
    .toLowerCase()
    .replace(/[^a-z0-9']+/g, '-') // Allow apostrophes and replace other non-alphanumeric characters with hyphens
    .replace(/(^-|-$)+/g, ''); // Remove leading or trailing hyphens
};

// Array of category labels
const categoryLabels = [
  'Access to Education',
  'Agriculture Innovation',
  'Animal Welfare',
  'Arts and Culture',
  'Arts Education',
  'Carbon Footprint Reduction',
  'Charity',
  'Civic Engagement',
  'Clean Energy',
  'Clean Water',
  'Climate Change',
  'Community Empowerment',
  'Community Health',
  'Community Support',
  'Crisis Response',
  'Cultural Preservation',
  'Digital Literacy',
  'Disability Support',
  'Disaster Preparedness',
  'Eco-Tourism',
  'Economic Development',
  'Education',
  'Elderly Care',
  'Energy Efficiency',
  'Environment',
  'Environmental Justice',
  'Family Services',
  'Financial Literacy',
  'Food Security',
  'Forestry Management',
  'Gender Equality',
  'Green Architecture',
  'Health',
  'Honor & Memorial',
  'Housing and Homelessness',
  'Humanitarian Aid',
  'Innovation and Research',
  'Innovation in Education',
  'Job Creation',
  'Local Business Support',
  'Local Farmers Support',
  'Marine Conservation',
  'Organic Farming',
  'Peer Support',
  'Plastic Recycling',
  'Poverty Reduction',
  'Public Health',
  'Public Safety',
  'Public Transport',
  'Renewable Energy',
  'Rural Development',
  'Social Enterprise',
  'Sports and Recreation',
  'Sustainable Agriculture',
  'Sustainable Transport',
  'Technology',
  'Urban Development',
  'Urban Farming',
  'Veterans Support',
  'Water and Sanitation',
  'Wildlife Conservation',
  'Women’s Empowerment',
  'Youth Development',
  'AI & Machine Learning',
  'Augmented Reality',
  'Biotechnology',
  'Blockchain & Crypto',
  'Clean Energy Tech',
  'Climate Tech',
  'Consumer Apps',
  'Creator Economy',
  'Cybersecurity',
  'Data Analytics',
  'Developer Tools',
  'Digital Health',
  'EdTech',
  'E-commerce',
  'Enterprise Software',
  'FinTech',
  'FoodTech',
  'Future of Work',
  'Gaming',
  'GreenTech',
  'Hardware',
  'HealthTech',
  'Impact Investing',
  'Industrial Tech',
  'InsurTech',
  'IoT',
  'LegalTech',
  'Logistics',
  'Marketplaces',
  'Mobility',
  'NFTs & Web3',
  'PropTech',
  'Quantum Computing',
  'Real Estate Tech',
  'Robotics',
  'SaaS',
  'SpaceTech',
  'SportsTech',
  'Supply Chain Tech',
  'Sustainability',
  'Telecom',
  'TravelTech',
  'Virtual Reality',
  'Wearables',
  'AgTech',
  'B2B Software',
  'Cloud Computing',
  'Crowdfunding Platforms',
  'Digital Banking',
  'Digital Media',
  'FemTech',
  'GovTech',
  'HR Tech',
  'MarTech',
  'Micro-investing',
  'Open Source',
  'Payments',
  'Personal Finance',
  'Retail Tech',
  'Smart Cities',
  'Social Impact',
  'Social Networking',
  'Voice Technology',
];

export const categoriesWithIcons: Category[] = [
  {
    label: 'Access to Education',
    value: slugify('Access to Education'),
    icon: <FaBook className="w-4 h-4 text-blue-500" />,
  },
  {
    label: 'Agriculture Innovation',
    value: slugify('Agriculture Innovation'),
    icon: <FaSeedling className="w-4 h-4 text-green-500" />,
  },
  {
    label: 'Animal Welfare',
    value: slugify('Animal Welfare'),
    icon: <FaPaw className="w-4 h-4 text-orange-500" />,
  },
  {
    label: 'Arts and Culture',
    value: slugify('Arts and Culture'),
    icon: <FaPalette className="w-4 h-4 text-purple-500" />,
  },
  {
    label: 'Arts Education',
    value: slugify('Arts Education'),
    icon: <FaMusic className="w-4 h-4 text-pink-500" />,
  },
  {
    label: 'Carbon Footprint Reduction',
    value: slugify('Carbon Footprint Reduction'),
    icon: <FaTree className="w-4 h-4 text-emerald-500" />,
  },
  {
    label: 'Charity',
    value: slugify('Charity'),
    icon: <FaHandsHelping className="w-4 h-4 text-teal-500" />,
  },
  {
    label: 'Civic Engagement',
    value: slugify('Civic Engagement'),
    icon: <FaUsers className="w-4 h-4 text-indigo-500" />,
  },
  {
    label: 'Clean Energy',
    value: slugify('Clean Energy'),
    icon: <FaLightbulb className="w-4 h-4 text-yellow-400" />,
  },
  {
    label: 'Clean Water',
    value: slugify('Clean Water'),
    icon: <FaTint className="w-4 h-4 text-blue-400" />,
  },
  {
    label: 'Climate Change',
    value: slugify('Climate Change'),
    icon: <FaCloudSunRain className="w-4 h-4 text-gray-400" />,
  },
  {
    label: 'Community Empowerment',
    value: slugify('Community Empowerment'),
    icon: <FaHandshake className="w-4 h-4 text-green-400" />,
  },
  {
    label: 'Community Health',
    value: slugify('Community Health'),
    icon: <FaHeartbeat className="w-4 h-4 text-red-400" />,
  },
  {
    label: 'Community Support',
    value: slugify('Community Support'),
    icon: <FaHandHoldingHeart className="w-4 h-4 text-pink-400" />,
  },
  {
    label: 'Crisis Response',
    value: slugify('Crisis Response'),
    icon: <FaFirstAid className="w-4 h-4 text-red-600" />,
  },
  {
    label: 'Cultural Preservation',
    value: slugify('Cultural Preservation'),
    icon: <FaMonument className="w-4 h-4 text-amber-500" />,
  },
  {
    label: 'Digital Literacy',
    value: slugify('Digital Literacy'),
    icon: <FaLaptop className="w-4 h-4 text-blue-600" />,
  },
  {
    label: 'Disability Support',
    value: slugify('Disability Support'),
    icon: <FaWheelchair className="w-4 h-4 text-gray-600" />,
  },
  {
    label: 'Disaster Preparedness',
    value: slugify('Disaster Preparedness'),
    icon: <FaBriefcase className="w-4 h-4 text-gray-700" />,
  },
  {
    label: 'Eco-Tourism',
    value: slugify('Eco-Tourism'),
    icon: <FaTree className="w-4 h-4 text-green-600" />,
  },
  {
    label: 'Economic Development',
    value: slugify('Economic Development'),
    icon: <FaCity className="w-4 h-4 text-purple-600" />,
  },
  {
    label: 'Education',
    value: slugify('Education'),
    icon: <FaBook className="w-4 h-4 text-blue-700" />,
  },
  {
    label: 'Elderly Care',
    value: slugify('Elderly Care'),
    icon: <FaUserShield className="w-4 h-4 text-gray-700" />,
  },
  {
    label: 'Energy Efficiency',
    value: slugify('Energy Efficiency'),
    icon: <FaSolarPanel className="w-4 h-4 text-yellow-600" />,
  },
  {
    label: 'Environment',
    value: slugify('Environment'),
    icon: <FaLeaf className="w-4 h-4 text-green-700" />,
  },
  {
    label: 'Environmental Justice',
    value: slugify('Environmental Justice'),
    icon: <FaRecycle className="w-4 h-4 text-green-500" />,
  },
  {
    label: 'Family Services',
    value: slugify('Family Services'),
    icon: <FaHandsHelping className="w-4 h-4 text-teal-600" />,
  },
  {
    label: 'Financial Literacy',
    value: slugify('Financial Literacy'),
    icon: <FaMoneyBillWave className="w-4 h-4 text-green-800" />,
  },
  {
    label: 'Food Security',
    value: slugify('Food Security'),
    icon: <FaFish className="w-4 h-4 text-blue-800" />,
  },
  {
    label: 'Forestry Management',
    value: slugify('Forestry Management'),
    icon: <FaTree className="w-4 h-4 text-green-800" />,
  },
  {
    label: 'Gender Equality',
    value: slugify('Gender Equality'),
    icon: <FaFemale className="w-4 h-4 text-pink-600" />,
  },
  {
    label: 'Green Architecture',
    value: slugify('Green Architecture'),
    icon: <FaBuilding className="w-4 h-4 text-green-900" />,
  },
  {
    label: 'Health',
    value: slugify('Health'),
    icon: <FaHeartbeat className="w-4 h-4 text-red-700" />,
  },
  {
    label: 'Honor & Memorial',
    value: slugify('Honor & Memorial'),
    icon: <FaRing className="w-4 h-4 text-gray-800" />,
  },
  {
    label: 'Housing and Homelessness',
    value: slugify('Housing and Homelessness'),
    icon: <FaHome className="w-4 h-4 text-blue-900" />,
  },
  {
    label: 'Humanitarian Aid',
    value: slugify('Humanitarian Aid'),
    icon: <FaFirstAid className="w-4 h-4 text-red-800" />,
  },
  {
    label: 'Innovation and Research',
    value: slugify('Innovation and Research'),
    icon: <FaMicroscope className="w-4 h-4 text-purple-800" />,
  },
  {
    label: 'Innovation in Education',
    value: slugify('Innovation in Education'),
    icon: <FaLightbulb className="w-4 h-4 text-yellow-700" />,
  },
  {
    label: 'Job Creation',
    value: slugify('Job Creation'),
    icon: <FaBriefcase className="w-4 h-4 text-gray-800" />,
  },
  {
    label: 'Local Business Support',
    value: slugify('Local Business Support'),
    icon: <FaBuilding className="w-4 h-4 text-purple-900" />,
  },
  {
    label: 'Local Farmers Support',
    value: slugify('Local Farmers Support'),
    icon: <FaTractor className="w-4 h-4 text-green-900" />,
  },
  {
    label: 'Marine Conservation',
    value: slugify('Marine Conservation'),
    icon: <FaFish className="w-4 h-4 text-blue-900" />,
  },
  {
    label: 'Organic Farming',
    value: slugify('Organic Farming'),
    icon: <FaSeedling className="w-4 h-4 text-green-700" />,
  },
  {
    label: 'Peer Support',
    value: slugify('Peer Support'),
    icon: <FaUsers className="w-4 h-4 text-blue-700" />,
  },
  {
    label: 'Plastic Recycling',
    value: slugify('Plastic Recycling'),
    icon: <FaRecycle className="w-4 h-4 text-green-600" />,
  },
  {
    label: 'Poverty Reduction',
    value: slugify('Poverty Reduction'),
    icon: <FaHandsHelping className="w-4 h-4 text-teal-700" />,
  },
  {
    label: 'Public Health',
    value: slugify('Public Health'),
    icon: <FaHeartbeat className="w-4 h-4 text-red-700" />,
  },
  {
    label: 'Public Safety',
    value: slugify('Public Safety'),
    icon: <FaShieldAlt className="w-4 h-4 text-gray-700" />,
  },
  {
    label: 'Public Transport',
    value: slugify('Public Transport'),
    icon: <FaBus className="w-4 h-4 text-blue-700" />,
  },
  {
    label: 'Renewable Energy',
    value: slugify('Renewable Energy'),
    icon: <FaSolarPanel className="w-4 h-4 text-yellow-700" />,
  },
  {
    label: 'Rural Development',
    value: slugify('Rural Development'),
    icon: <FaTractor className="w-4 h-4 text-green-700" />,
  },
  {
    label: 'Social Enterprise',
    value: slugify('Social Enterprise'),
    icon: <FaBuilding className="w-4 h-4 text-purple-700" />,
  },
  {
    label: 'Sports and Recreation',
    value: slugify('Sports and Recreation'),
    icon: <FaFootballBall className="w-4 h-4 text-orange-700" />,
  },
  {
    label: 'Sustainable Agriculture',
    value: slugify('Sustainable Agriculture'),
    icon: <FaSeedling className="w-4 h-4 text-green-700" />,
  },
  {
    label: 'Sustainable Transport',
    value: slugify('Sustainable Transport'),
    icon: <FaBus className="w-4 h-4 text-blue-700" />,
  },
  {
    label: 'Technology',
    value: slugify('Technology'),
    icon: <FaLaptop className="w-4 h-4 text-blue-700" />,
  },
  {
    label: 'Urban Development',
    value: slugify('Urban Development'),
    icon: <FaCity className="w-4 h-4 text-purple-700" />,
  },
  {
    label: 'Urban Farming',
    value: slugify('Urban Farming'),
    icon: <FaSeedling className="w-4 h-4 text-green-700" />,
  },
  {
    label: 'Veterans Support',
    value: slugify('Veterans Support'),
    icon: <FaUserShield className="w-4 h-4 text-gray-700" />,
  },
  {
    label: 'Water and Sanitation',
    value: slugify('Water and Sanitation'),
    icon: <FaWater className="w-4 h-4 text-blue-700" />,
  },
  {
    label: 'Wildlife Conservation',
    value: slugify('Wildlife Conservation'),
    icon: <FaPaw className="w-4 h-4 text-orange-700" />,
  },
  {
    label: "Women's Empowerment",
    value: slugify('Women’s Empowerment'),
    icon: <FaFemale className="w-4 h-4 text-pink-700" />,
  },
  {
    label: 'Youth Development',
    value: slugify('Youth Development'),
    icon: <FaChild className="w-4 h-4 text-yellow-700" />,
  },
  {
    label: 'AI & Machine Learning',
    value: slugify('AI & Machine Learning'),
    icon: <FaRobot className="w-4 h-4 text-purple-500" />,
  },
  {
    label: 'Augmented Reality',
    value: slugify('Augmented Reality'),
    icon: <FaMobile className="w-4 h-4 text-blue-500" />,
  },
  {
    label: 'Biotechnology',
    value: slugify('Biotechnology'),
    icon: <FaMedkit className="w-4 h-4 text-red-500" />,
  },
  {
    label: 'Blockchain & Crypto',
    value: slugify('Blockchain & Crypto'),
    icon: <FaBitcoin className="w-4 h-4 text-yellow-500" />,
  },
  {
    label: 'Clean Energy Tech',
    value: slugify('Clean Energy Tech'),
    icon: <FaSolarPanel className="w-4 h-4 text-green-500" />,
  },
  {
    label: 'Climate Tech',
    value: slugify('Climate Tech'),
    icon: <FaLeaf className="w-4 h-4 text-emerald-500" />,
  },
  {
    label: 'Consumer Apps',
    value: slugify('Consumer Apps'),
    icon: <FaMobile className="w-4 h-4 text-blue-400" />,
  },
  {
    label: 'Creator Economy',
    value: slugify('Creator Economy'),
    icon: <FaUsers className="w-4 h-4 text-pink-500" />,
  },
  {
    label: 'Cybersecurity',
    value: slugify('Cybersecurity'),
    icon: <FaLock className="w-4 h-4 text-gray-500" />,
  },
  {
    label: 'Data Analytics',
    value: slugify('Data Analytics'),
    icon: <FaChartLine className="w-4 h-4 text-indigo-500" />,
  },
  {
    label: 'Developer Tools',
    value: slugify('Developer Tools'),
    icon: <FaCode className="w-4 h-4 text-gray-600" />,
  },
  {
    label: 'Digital Health',
    value: slugify('Digital Health'),
    icon: <FaMedkit className="w-4 h-4 text-red-400" />,
  },
  {
    label: 'EdTech',
    value: slugify('EdTech'),
    icon: <FaGraduationCap className="w-4 h-4 text-blue-600" />,
  },
  {
    label: 'E-commerce',
    value: slugify('E-commerce'),
    icon: <FaShoppingCart className="w-4 h-4 text-yellow-400" />,
  },
  {
    label: 'Enterprise Software',
    value: slugify('Enterprise Software'),
    icon: <FaBuilding className="w-4 h-4 text-gray-400" />,
  },
  {
    label: 'FinTech',
    value: slugify('FinTech'),
    icon: <FaMoneyBillWave className="w-4 h-4 text-green-400" />,
  },
  {
    label: 'FoodTech',
    value: slugify('FoodTech'),
    icon: <FaUtensils className="w-4 h-4 text-orange-400" />,
  },
  {
    label: 'Future of Work',
    value: slugify('Future of Work'),
    icon: <FaBriefcase className="w-4 h-4 text-purple-400" />,
  },
  {
    label: 'Gaming',
    value: slugify('Gaming'),
    icon: <FaGamepad className="w-4 h-4 text-red-600" />,
  },
  {
    label: 'GreenTech',
    value: slugify('GreenTech'),
    icon: <FaLeaf className="w-4 h-4 text-green-600" />,
  },
  {
    label: 'Hardware',
    value: slugify('Hardware'),
    icon: <FaMicrochip className="w-4 h-4 text-gray-700" />,
  },
  {
    label: 'HealthTech',
    value: slugify('HealthTech'),
    icon: <FaMedkit className="w-4 h-4 text-red-600" />,
  },
  {
    label: 'Impact Investing',
    value: slugify('Impact Investing'),
    icon: <FaSearchDollar className="w-4 h-4 text-teal-500" />,
  },
  {
    label: 'Industrial Tech',
    value: slugify('Industrial Tech'),
    icon: <FaIndustry className="w-4 h-4 text-gray-800" />,
  },
  {
    label: 'InsurTech',
    value: slugify('InsurTech'),
    icon: <FaShieldAlt className="w-4 h-4 text-blue-700" />,
  },
  {
    label: 'IoT',
    value: slugify('IoT'),
    icon: <FaSatelliteDish className="w-4 h-4 text-purple-600" />,
  },
  {
    label: 'LegalTech',
    value: slugify('LegalTech'),
    icon: <FaBalanceScale className="w-4 h-4 text-gray-700" />,
  },
  {
    label: 'Logistics',
    value: slugify('Logistics'),
    icon: <FaTruck className="w-4 h-4 text-orange-600" />,
  },
  {
    label: 'Marketplaces',
    value: slugify('Marketplaces'),
    icon: <FaShoppingCart className="w-4 h-4 text-yellow-600" />,
  },
  {
    label: 'Mobility',
    value: slugify('Mobility'),
    icon: <FaCar className="w-4 h-4 text-blue-800" />,
  },
  {
    label: 'NFTs & Web3',
    value: slugify('NFTs & Web3'),
    icon: <FaQrcode className="w-4 h-4 text-purple-700" />,
  },
  {
    label: 'PropTech',
    value: slugify('PropTech'),
    icon: <FaHome className="w-4 h-4 text-green-700" />,
  },
  {
    label: 'Quantum Computing',
    value: slugify('Quantum Computing'),
    icon: <FaMicrochip className="w-4 h-4 text-indigo-700" />,
  },
  {
    label: 'Real Estate Tech',
    value: slugify('Real Estate Tech'),
    icon: <FaBuilding className="w-4 h-4 text-blue-900" />,
  },
  {
    label: 'Robotics',
    value: slugify('Robotics'),
    icon: <FaRobot className="w-4 h-4 text-purple-800" />,
  },
  {
    label: 'SaaS',
    value: slugify('SaaS'),
    icon: <FaCloud className="w-4 h-4 text-blue-500" />,
  },
  {
    label: 'SpaceTech',
    value: slugify('SpaceTech'),
    icon: <FaSatelliteDish className="w-4 h-4 text-gray-900" />,
  },
  {
    label: 'SportsTech',
    value: slugify('SportsTech'),
    icon: <FaDumbbell className="w-4 h-4 text-orange-700" />,
  },
  {
    label: 'Supply Chain Tech',
    value: slugify('Supply Chain Tech'),
    icon: <FaTruck className="w-4 h-4 text-gray-800" />,
  },
  {
    label: 'Sustainability',
    value: slugify('Sustainability'),
    icon: <FaLeaf className="w-4 h-4 text-green-800" />,
  },
  {
    label: 'Telecom',
    value: slugify('Telecom'),
    icon: <FaSatelliteDish className="w-4 h-4 text-blue-700" />,
  },
  {
    label: 'TravelTech',
    value: slugify('TravelTech'),
    icon: <FaPlane className="w-4 h-4 text-indigo-600" />,
  },
  {
    label: 'Virtual Reality',
    value: slugify('Virtual Reality'),
    icon: <FaHeadset className="w-4 h-4 text-purple-500" />,
  },
  {
    label: 'Wearables',
    value: slugify('Wearables'),
    icon: <FaTshirt className="w-4 h-4 text-red-500" />,
  },
  {
    label: 'AgTech',
    value: slugify('AgTech'),
    icon: <FaSeedling className="w-4 h-4 text-green-600" />,
  },
  {
    label: 'B2B Software',
    value: slugify('B2B Software'),
    icon: <FaUserTie className="w-4 h-4 text-blue-600" />,
  },
  {
    label: 'Cloud Computing',
    value: slugify('Cloud Computing'),
    icon: <FaCloud className="w-4 h-4 text-blue-400" />,
  },
  {
    label: 'Crowdfunding Platforms',
    value: slugify('Crowdfunding Platforms'),
    icon: <FaHandshake className="w-4 h-4 text-green-500" />,
  },
  {
    label: 'Digital Banking',
    value: slugify('Digital Banking'),
    icon: <FaWallet className="w-4 h-4 text-blue-500" />,
  },
  {
    label: 'Digital Media',
    value: slugify('Digital Media'),
    icon: <FaPalette className="w-4 h-4 text-pink-500" />,
  },
  {
    label: 'FemTech',
    value: slugify('FemTech'),
    icon: <FaFemale className="w-4 h-4 text-pink-600" />,
  },
  {
    label: 'GovTech',
    value: slugify('GovTech'),
    icon: <FaBuilding className="w-4 h-4 text-gray-600" />,
  },
  {
    label: 'HR Tech',
    value: slugify('HR Tech'),
    icon: <FaUsers className="w-4 h-4 text-teal-500" />,
  },
  {
    label: 'MarTech',
    value: slugify('MarTech'),
    icon: <FaChartLine className="w-4 h-4 text-orange-500" />,
  },
  {
    label: 'Micro-investing',
    value: slugify('Micro-investing'),
    icon: <FaPiggyBank className="w-4 h-4 text-green-600" />,
  },
  {
    label: 'Open Source',
    value: slugify('Open Source'),
    icon: <FaCode className="w-4 h-4 text-red-600" />,
  },
  {
    label: 'Payments',
    value: slugify('Payments'),
    icon: <FaExchangeAlt className="w-4 h-4 text-blue-600" />,
  },
  {
    label: 'Personal Finance',
    value: slugify('Personal Finance'),
    icon: <FaRegMoneyBillAlt className="w-4 h-4 text-green-700" />,
  },
  {
    label: 'Retail Tech',
    value: slugify('Retail Tech'),
    icon: <FaShoppingCart className="w-4 h-4 text-yellow-600" />,
  },
  {
    label: 'Smart Cities',
    value: slugify('Smart Cities'),
    icon: <FaCity className="w-4 h-4 text-blue-700" />,
  },
  {
    label: 'Social Impact',
    value: slugify('Social Impact'),
    icon: <FaHandsHelping className="w-4 h-4 text-teal-600" />,
  },
  {
    label: 'Social Networking',
    value: slugify('Social Networking'),
    icon: <FaUsers className="w-4 h-4 text-blue-600" />,
  },
  {
    label: 'Voice Technology',
    value: slugify('Voice Technology'),
    icon: <FaMicrophone className="w-4 h-4 text-purple-600" />,
  },
];

// Generate categories using the slugify function
export const categories: Category[] = categoryLabels.map((label) => ({
  label,
  value: slugify(label),
}));

// Helper function to convert a slug into a normal label
export const deslugify = (slug: string): string => {
  return slug
    .split('-') // Split the slug by hyphens
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1)) // Capitalize each word
    .join(' ') // Join the words with spaces
    .replace(/ S /g, '’s '); // Replace " S " with "’s " to handle apostrophes correctly
};
